WITH LANCAMENTOS_BASE AS (
    SELECT 
        NUMNOTA, 
        RECNUM, 
        CODCONTA, 
        CODFORNEC, 
        CODFILIAL, 
        DTEMISSAO, 
        DTLANC, 
        DTVENC, 
        DTPAGTO, 
        DTCOMPETENCIA, 
        TIPOPARCEIRO, 
        INDICE, 
        DUPLIC, 
        VALOR, 
        VPAGO, 
        HISTORICO, 
        CODROTINACAD
    FROM cedep.PCLANC 
    WHERE DTLANC BETWEEN TO_DATE('{{ var("dt_inicio", "2020-01-01") }}', 'YYYY-MM-DD')
                AND TO_DATE('{{ var("dt_fim", "2025-12-31") }}', 'YYYY-MM-DD')
    
    UNION ALL
    
    SELECT 
        LA.NUMNOTA, 
        BA.RECNUM, 
        LA.CODCONTA, 
        LA.CODFORNEC, 
        LA.CODFILIAL, 
        LA.DTEMISSAO, 
        LA.DTLANC, 
        LA.DTVENC, 
        BA.DTPAGTO, 
        LA.DTCOMPETENCIA, 
        LA.TIPOPARCEIRO, 
        LA.INDICE, 
        LA.DUPLIC, 
        ((BA.VPAGO + NVL(BA.VLVARIACAOCAMBIAL, 0)) * (-1)) AS VALOR, 
        ((BA.VPAGO + NVL(BA.VLVARIACAOCAMBIAL, 0)) * (-1)) AS VPAGO, 
        'BX ADTO FORNEC REF LANC ' || A.RECNUMADIANTAMENTO || ' - PG ' || TO_CHAR(BA.DTPAGTO, 'DD/MM/YYYY') AS HISTORICO, 
        LA.CODROTINACAD
    FROM cedep.PCLANCADIANTFORNEC A
    JOIN cedep.PCLANC LA ON A.RECNUMADIANTAMENTO = LA.RECNUM
    JOIN cedep.PCLANC BA ON A.RECNUMPAGTO = BA.RECNUM
    WHERE A.DTESTORNO IS NULL 
        AND BA.DTPAGTO IS NOT NULL 
        AND BA.DTESTORNOBAIXA IS NULL 
        AND LA.CODFILIAL IN ('1', '10', '2', '3', '4', '7', '8', '9', '99') 
        AND A.DTLANC BETWEEN TO_DATE('{{ var("dt_inicio", "2020-01-01") }}', 'YYYY-MM-DD')
                AND TO_DATE('{{ var("dt_fim", "2025-12-31") }}', 'YYYY-MM-DD')
)
SELECT 
    LB.NUMNOTA,
    LB.RECNUM,
    LB.CODCONTA,
    LB.CODFORNEC,
    LB.CODFILIAL,
    LB.DTEMISSAO,
    LB.DTLANC,
    LB.DTVENC,
    LB.DTPAGTO,
    LB.DTCOMPETENCIA,
    LB.TIPOPARCEIRO,
    LB.INDICE,
    LB.DUPLIC,
    LB.VALOR,
    LB.VPAGO,
    LB.HISTORICO,
    LB.CODROTINACAD,
    NVL(CC.CODIGOCENTROCUSTO, '20.000') AS CODIGOCENTROCUSTO,
    NVL(CC.PERCRATEIO, 100) AS PERCRATEIO,
    NVL(CC.VALOR, LB.VALOR) AS VALOR_RATEADO_CC,
    (LB.VALOR * NVL(CC.PERCRATEIO, 100) / 100) AS VALOR_RATEADO_CALC,
    (LB.VPAGO * NVL(CC.PERCRATEIO, 100) / 100) AS VPAGO_RATEADO_CALC
FROM LANCAMENTOS_BASE LB
LEFT JOIN cedep.PCRATEIOCENTROCUSTO CC ON LB.RECNUM = CC.RECNUM
ORDER BY LB.RECNUM, CC.CODIGOCENTROCUSTO