SELECT
    CODCLI,
    CLIENTE,
    DTPRIMCOMPRA,

    CASE
        WHEN DTPRIMCOMPRA IS NULL
          OR EXTRACT(YEAR FROM DTPRIMCOMPRA) < 1900
          OR EXTRACT(YEAR FROM DTPRIMCOMPRA) > EXTRACT(YEAR FROM SYSDATE)
        THEN DATE '1900-01-01'
        ELSE DTPRIMCOMPRA
    END AS DTPRIMCOMPRA_TRATADA,

    INICIOATIV,

    CASE
        WHEN INICIOATIV IS NULL
          OR EXTRACT(YEAR FROM INICIOATIV) < 1900
          OR EXTRACT(YEAR FROM INICIOATIV) > EXTRACT(YEAR FROM SYSDATE)
        THEN DATE '1900-01-01'
        ELSE INICIOATIV
    END AS INICIOATIV_TRATADA,

    BAIRROCOM,
    TIPOFJ

FROM {{ source('cedep', 'pcclient')}} 
