SELECT 
    LB.RECNUM,
    LB.CODCONTA,
    LB.CODFORNEC,
    LB.CODFILIAL,
    LB.DTEMISSAO,
    LB.DTLANC,
    LB.DTVENC,
    LB.DTPAGTO,
    LB.DTCOMPETENCIA,
    LB.VALOR,
    LB.VPAGO,
    NVL(CC.CODIGOCENTROCUSTO, '99.999') AS CODIGOCENTROCUSTO,
    NVL(CC.PERCRATEIO, 100) AS PERCRATEIO,
    NVL(CC.VALOR, LB.VALOR) AS VALOR_RATEADO_CC,
    (LB.VALOR * NVL(CC.PERCRATEIO, 100) / 100) AS VALOR_RATEADO_CALC,
    (LB.VPAGO * NVL(CC.PERCRATEIO, 100) / 100) AS VPAGO_RATEADO_CALC
FROM {{ ref('int_contasapagar') }} LB
LEFT JOIN {{ ref('stg_rateio_centro_custo') }} CC 
    ON LB.RECNUM = CC.RECNUM
WHERE {{ filtro_periodo('LB.DTLANC') }}    
ORDER BY LB.RECNUM, CC.CODIGOCENTROCUSTO
