SELECT 
    RECNUM,
    NUMNOTA,
    DUPLIC,
    CODCONTA,
    CODFORNEC,
    CODFILIAL,
    DTEMISSAO,
    DTLANC,
    DTVENC,
    DTPAGTO,
    DTCOMPETENCIA,
    VALOR,
    VPAGO,
    CASE
        WHEN TIPOLANC = 'C' THEN 'CONFIRMADO'
        WHEN TIPOLANC = 'P' THEN 'PROVISIONADO'
        ELSE 'NÃO INFORMADO'
    END AS TIPOLANC
FROM {{ ref('int_contasapagar') }}
WHERE {{ filtro_periodo('DTEMISSAO') }} 