
version: 2

models:
  - name: stg_clientes
    description: "Tabela de clientes"
    columns:
      - name: CODCLI
        description: "Código do cliente"
        data_tests:
          - unique
          - not_null
      - name: CLIENTE
        description: "Nome do cliente"

  - name: stg_cobranca
    description: "Tabela de tipos de cobranças"
    columns:
      - name: CODCOB
        description: "Código de cobrança"
        data_tests:
          - unique
          - not_null
      - name: COBRANCA
        description: "Tipo de cobrança"

  - name: stg_filiais
    description: "Tabela de filiais"
    columns:
      - name: CODIGO
        description: "Código da filial"
        data_tests:
          - unique
          - not_null
      - name: RAZAOSOCIAL
        description: "Razão social da filial"
      - name: ENDERECO
        description: "Endereço da filial"
      - name: CIDADE
        description: "Cidade da filial"

  - name: stg_supervisores
    description: "Tabela de supervisores"
    columns:
      - name: CODSUPERVISOR
        description: "Código de supervisor"
        data_tests:
          - unique
          - not_null
      - name: NOME
        description: "Nome do supervisor"

  - name: stg_vendedores
    description: "Tabela de vendedores"
    columns:
      - name: CODUSUR
        description: "Código de vendedor"
        data_tests:
          - unique
          - not_null
      - name: NOME
        description: "Nome do vendedor"
      - name: CODSUPERVISOR
        description: "Código do supervisor do vendedor"

  - name: stg_pcprest
    description: "Tabela fato de lançamentos de contas a receber"